### ISSUE TITLE
Feature: File browser

### ISSUE THREAD

**Issue by ieivanov** [saalfeldlab/n5-ij#22]
It would be great if the file browser starts in the last selected data path, rather than Documents (on Windows). This will make browsing through multiple datasets easier.

**Comment by bogovicj** [comment]
> the file browser starts in the last selected data path

I assume you mean the last path that was navigated to from _imageJ_ right?

**Comment by ieivanov** [comment]
That's correct. Or maybe it will be simpler to start from the data path that's currently displayed in the GUI window. In most cases that will be the last dataset that was opened. This feature can also be used to set a convenient staring point for file navigation.

Thanks!

**Comment by bogovicj** [comment]
This will be in the next release. Thanks @ieivanov !
