### ISSUE TITLE
Enhancement: Detect zarr hierarchical structure

### ISSUE THREAD

**Issue by ieivanov** [saalfeldlab/n5-ij#23]
Currently the button "Detect dataset" does not detect hierarchical structure of zarr datasets (https://zarr.readthedocs.io/en/stable/tutorial.html#groups). Zarr arrays contained in the datasets are correctly detected and opened if the user navigates to them through the hierarchical structure. It would be convenient if the user can open zarr arrays contained within the structure, in a similar manner to the N5 example in the README.

**Comment by ieivanov** [comment]
The zarr hierarchical structure is correctly detected if the root folder end with `.zarr`. This seems to be a convention that I was not aware of. I think this issue can be closed.

**Comment by bogovicj** [comment]
Thanks for following up.  Indeed, at the moment we're strict about the zarr root directories ending in `.zarr` 
I'll close this issue.
