### ISSUE TITLE
Feature: Self-hosted S3 compatible object store

### ISSUE THREAD

**Issue by verbunk** [saalfeldlab/n5-ij#26]
Hey Folks, 

I'd like to request a new feature extension to the S3 i/o module -- support for named URLs to support self-hosted store implementations (like MinIO). A lot of file storage kit these days comes with S3 compatible stores so it would be a useful feature to be able to use with these.

**Comment by bogovicj** [comment]
Hi @verbunk ,

Interesting idea. I'm unlikely to look into this near-term, but am very happy to leave this open for the future.

I expect that this will not be hard to implement for someone familiar with the S3 compatible stores. If this is high-priority for you, I'm happy to help point you (or anyone willing to contribute) to where the changes will be needed and to go through a PR.

**Comment by joshmoore** [comment]
Having gone through this recently a few heads up:
 * using Amazon's SDK, setting `withEndpointConfiguration` tends to work pretty well though `.withPathStyleAccessEnabled(true)` is needed.
 * using a Java `FileSystem` I didn't find a way around needing to be pass arbitrary options as in ([bioformats2raw](https://github.com/glencoesoftware/bioformats2raw/blob/master/src/main/java/com/glencoesoftware/bioformats2raw/Converter.java#L133)

**Comment by bogovicj** [comment]
This now works, given the most recent release:
https://github.com/saalfeldlab/n5-ij/releases/tag/n5-ij-3.2.6
