### ISSUE TITLE
ImageJ Macro Recording fails to record virtual & crop options

### ISSUE THREAD

**Issue by StephanPreibisch** [saalfeldlab/n5-ij#27]
Hi, something we should fix ... if recorded these options (virtual/crop) do not appear.

Thanks so much, Stephan

**Comment by StephanPreibisch** [comment]
It is worse, it sometimes record and sometimes doesn't ...

**Comment by StephanPreibisch** [comment]
couldn't reproduce the behavior. I suspect it is a clash between the GenericDialog that is called during the "crop" option and the recorder being set by hand. Because it somehow tries to record from the GenericDialog

**Comment by bogovicj** [comment]
Thanks for reporting.

**Comment by StephanPreibisch** [comment]
the pull request hopefully fixes it

**Comment by bogovicj** [comment]
im optimistic that it will

**Comment by bogovicj** [comment]
Looking good now.  Thanks again @StephanPreibisch .

**Comment by StephanPreibisch** [comment]
Thanks for making this super useful frontend!

So macro processing is fixed @krokicki ...

**Comment by krokicki** [comment]
Thank you @StephanPreibisch !
