### ISSUE TITLE
metadata parsing post n5 attribute cache

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/n5-ij#30]
## Use cases

`n5-ij` needs:
* read metadata from an n5 group or dataset
*  write metadata into an n5 group or dataset
*  read metadata from an `ImagePlus`
*  write metadata into `ImagePlus`
*  Create a tree of all datasets in an n5 container down to the datasets
   * `n5.deepListDatasets` creates a flat list from which we can build a tree

`n5-viewer` additionally needs:
* identify and open multiscale groups of datasets

@cmhulbert 
what does paintera need that's not the above

**Comment by cmhulbert** [comment]
Some of the issues with the current implementation should be solved by the attribute caching. For `Paintera`, I think we'll additionally want:

- access to `attributes.json` of a group/non-dataset
- move `getAttributes()` into a `N5DatasetMetadata` itnerface which inherits from `N5Metadata`
  - If we do this, maybe could get rid of `isDataset` in favor of a type check for implementing `N5DatasetMetadata`, unless we expect it could still be null
- If we want `Paintera` to depend on the existing metadata parsers here (for COSEM, for example) they would need to not implement `ImagePlus` directly, but maybe have a ImagePlus compliant subclass specific to `n5-ij`?

The last point brings up the question of where the Metadata logic will reside, or if we just duplicate the logic in Paintera

**Comment by bogovicj** [comment]
Working in the [`cache-attrs` branch](https://github.com/saalfeldlab/n5-ij/tree/cache-attrs):

> move getAttributes() into a N5DatasetMetadata interface which inherits from N5Metadata

I agree that this is sensible and have done it.  Have not yet made `N5DatasetMetadata`, but I'm open to it.  Let's discuss more.
Also have not yet split parsing and metadata storage objects, but think that's likely worth doing.  But will put that off for now.

Main progress so far is separation of discovery and parsing as shown [here](https://github.com/saalfeldlab/n5-ij/blob/cache-attrs/src/main/java/org/janelia/saalfeldlab/n5/N5DatasetDiscoverer.java#L241-L257).  So (for `n5-ij`) the code looks like this:
```java
// find a set of paths
String[] datasetPaths = n5.deepList( base, executor );

// build a tree from the paths
N5TreeNode root = N5TreeNode.fromFlatList( base, datasetPaths, groupSeparator );

// parse metadata and groups
parseMetadataRecursive( root );
parseGroupsRecursive( root );

```
where in this example the set of metadata and group parsers are stored in local fields.  There are also some [static methods in `N5DatasetDiscoverer`](https://github.com/saalfeldlab/n5-ij/blob/cache-attrs/src/main/java/org/janelia/saalfeldlab/n5/N5DatasetDiscoverer.java#L361-L437) (which need some cleaning up, but may still be useful).

Metadata parsers can be applied on any group (not just datasets) as shown in [this test using paintera-sytle metadata](https://github.com/saalfeldlab/n5-ij/blob/cache-attrs/src/test/java/org/janelia/saalfeldlab/n5/metadata/MetadataTests.java#L184-L209)

**Comment by bogovicj** [comment]
This issue is no longer relevant because caching is implemented and new version released.
