### ISSUE TITLE
Feature request: option to generate multichannel/multiscale during export

### ISSUE THREAD

**Issue by krokicki** [saalfeldlab/n5-ij#53]
When exporting N5 it would be nice to have an option to generate a multichannel/multiscale representation as supported by BDV. Meaning:
```
c0
    s0
    s1
    s2
c1
    s0
    s1
    s2
```
Etc. Along with the associated multiscale metadata. 

I believe that BigStitcher already has this option when resaving to N5, so maybe code could be borrowed from there.

**Comment by bogovicj** [comment]
Done
