### ISSUE TITLE
Issue opining up h5 file using N5 plugin - images are blank

### ISSUE THREAD

**Issue by Chriswang0904** [saalfeldlab/n5-ij#80]
Hi!
I'm trying to open some h5 file through import->N5 on image J, but the images turned up to be blank. The file is able to open up properly using the import->HDF5. I wonder what the issue is? 

Context: My dataset is very large and exceeds the HDF5 plugin size limit, so I want to use the N5 plugin and use its virtual stack function. The N5 opens the file as blank no matter if the file size is big or small, or if I use virtual stack or not.

Thank you very much!

<img width="617" alt="Screenshot 2024-05-14 at 4 25 38 PM" src="https://github.com/saalfeldlab/n5-ij/assets/109468722/0fc850bc-df3d-4a2c-80ac-9b3853096916">
<img width="571" alt="Screenshot 2024-05-14 at 4 25 44 PM" src="https://github.com/saalfeldlab/n5-ij/assets/109468722/cb23e5e6-32af-4315-b08f-5663bdb9bb31">
<img width="589" alt="Screenshot 2024-05-14 at 4 25 55 PM" src="https://github.com/saalfeldlab/n5-ij/assets/109468722/a294f936-df0c-47ff-8ecd-32b0a3690019">
<img width="419" alt="Screenshot 2024-05-14 at 4 26 22 PM" src="https://github.com/saalfeldlab/n5-ij/assets/109468722/1ef7d1b3-af50-439b-a871-fef9428d8d61">

**Comment by bogovicj** [comment]
Hi @Chriswang0904 ,

It may be that the brightness / contrast is set strangely and not that the image data is missing.
After opening the image, can you please try `Image > Adjust > Brightness/Contrast` and hit `Auto`. 
Please let us know if that helps or if the issue persists.

**Comment by Chriswang0904** [comment]
> Hi @Chriswang0904 ,
> 
> It may be that the brightness / contrast is set strangely and not that the image data is missing. After opening the image, can you please try `Image > Adjust > Brightness/Contrast` and hit `Auto`. Please let us know if that helps or if the issue persists.

This worked… thank you!!

**Comment by bogovicj** [comment]
Thanks for reporting back!

In the future, I'll try to have the plugin pick reasonable brightness / contrast values after opening...
